/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author USER
 */
import java.sql.*;
import javax.swing.*;
public class customer_search extends javax.swing.JFrame {
  
    
    Connection con;
    PreparedStatement pst;

    /**
     * Creates new form customer_search
     */
    public customer_search() {
        initComponents();
        con=SQLCON.connect();
        
        try
        {
            Statement st =con.createStatement();
            
            String sql = "select * from customer_details";
            ResultSet rs=st.executeQuery(sql);
            
            while(rs.next())
            {
                txtcustomer_regno.getText();
            }
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlowner_details = new javax.swing.JPanel();
        lblcustomer_details = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lblnic = new javax.swing.JLabel();
        txtnic = new javax.swing.JTextField();
        lbladress = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        lblphone = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        lblpickup_date = new javax.swing.JLabel();
        lblpickup_date1 = new javax.swing.JLabel();
        txtpickup_time2 = new javax.swing.JTextField();
        txtpickup_time3 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblpayment = new javax.swing.JLabel();
        lbldeposit1 = new javax.swing.JLabel();
        lbldeposit2 = new javax.swing.JLabel();
        btnpackeges = new javax.swing.JButton();
        lblpackege = new javax.swing.JLabel();
        txtpackege = new javax.swing.JTextField();
        pnlvehicle_details1 = new javax.swing.JPanel();
        lblmodel = new javax.swing.JLabel();
        lblmodel1 = new javax.swing.JLabel();
        lblno = new javax.swing.JLabel();
        lblveviclename = new javax.swing.JLabel();
        txtvehicle_name = new javax.swing.JTextField();
        txtmodel = new javax.swing.JTextField();
        txtyear = new javax.swing.JTextField();
        txtnumber = new javax.swing.JTextField();
        lblregno = new javax.swing.JLabel();
        txtreg_no = new javax.swing.JTextField();
        txtdriven = new javax.swing.JTextField();
        lblseats = new javax.swing.JLabel();
        txtseats = new javax.swing.JTextField();
        lbltype = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        btnsearch = new javax.swing.JButton();
        txtcustomer_regno = new javax.swing.JTextField();
        lblcustomer_regno = new javax.swing.JLabel();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        lblbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add New Customer");
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        pnlowner_details.setBackground(new java.awt.Color(104, 94, 137));
        pnlowner_details.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 0), new java.awt.Color(255, 153, 0)));
        pnlowner_details.setOpaque(false);

        lblcustomer_details.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblcustomer_details.setForeground(new java.awt.Color(204, 204, 255));
        lblcustomer_details.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcustomer_details.setText("Coustomer details");
        lblcustomer_details.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblname.setForeground(new java.awt.Color(255, 255, 255));
        lblname.setText("Name :");

        txtname.setBackground(new java.awt.Color(255, 206, 108));

        lblnic.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblnic.setForeground(new java.awt.Color(255, 255, 255));
        lblnic.setText("NIC :");

        txtnic.setBackground(new java.awt.Color(255, 206, 108));
        txtnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnicActionPerformed(evt);
            }
        });

        lbladress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbladress.setForeground(new java.awt.Color(255, 255, 255));
        lbladress.setText("Adress :");

        txtaddress.setBackground(new java.awt.Color(255, 206, 108));
        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });

        lblphone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblphone.setForeground(new java.awt.Color(255, 255, 255));
        lblphone.setText("Phone NO. :");

        txtphone.setBackground(new java.awt.Color(255, 206, 108));
        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });

        lblpickup_date.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblpickup_date.setForeground(new java.awt.Color(255, 255, 255));
        lblpickup_date.setText("Date :");

        lblpickup_date1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblpickup_date1.setForeground(new java.awt.Color(255, 255, 255));
        lblpickup_date1.setText("Date :");

        txtpickup_time2.setBackground(new java.awt.Color(255, 206, 108));

        txtpickup_time3.setBackground(new java.awt.Color(255, 206, 108));

        lblpayment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblpayment.setForeground(new java.awt.Color(204, 204, 255));
        lblpayment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpayment.setText("Payment Details");
        lblpayment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbldeposit1.setText("Diposit :");

        lbldeposit2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldeposit2.setForeground(new java.awt.Color(153, 0, 0));
        lbldeposit2.setText("Rs. 6000 for 24");

        btnpackeges.setBackground(new java.awt.Color(0, 102, 102));
        btnpackeges.setForeground(new java.awt.Color(51, 51, 255));
        btnpackeges.setText("Packege");
        btnpackeges.setEnabled(false);

        lblpackege.setText("Packege :");

        txtpackege.setBackground(new java.awt.Color(255, 206, 108));

        javax.swing.GroupLayout pnlowner_detailsLayout = new javax.swing.GroupLayout(pnlowner_details);
        pnlowner_details.setLayout(pnlowner_detailsLayout);
        pnlowner_detailsLayout.setHorizontalGroup(
            pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                        .addComponent(lblpackege, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnpackeges)
                        .addGap(97, 97, 97))
                    .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                        .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                                .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblphone, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblpickup_date1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtpickup_time3, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                                    .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtphone))))
                            .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                                    .addComponent(lbladress, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtaddress))
                                .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                                    .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                                            .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(26, 26, 26))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlowner_detailsLayout.createSequentialGroup()
                                            .addComponent(lblnic, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblcustomer_details, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(lblpayment, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                                .addComponent(lbldeposit1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtpackege)
                                    .addComponent(lbldeposit2, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
                            .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                                .addComponent(lblpickup_date, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtpickup_time2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(127, Short.MAX_VALUE))))
        );
        pnlowner_detailsLayout.setVerticalGroup(
            pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcustomer_details, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnic))
                .addGap(18, 18, 18)
                .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbladress)
                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblphone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpickup_time2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpickup_date))
                .addGap(20, 20, 20)
                .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpickup_time3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpickup_date1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblpayment, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpackege)
                    .addComponent(btnpackeges)
                    .addComponent(txtpackege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldeposit1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldeposit2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        getContentPane().add(pnlowner_details);
        pnlowner_details.setBounds(50, 80, 444, 444);

        pnlvehicle_details1.setBackground(new java.awt.Color(104, 94, 137));
        pnlvehicle_details1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 0), new java.awt.Color(255, 153, 0)));
        pnlvehicle_details1.setOpaque(false);

        lblmodel.setBackground(new java.awt.Color(255, 255, 255));
        lblmodel.setForeground(new java.awt.Color(255, 255, 255));
        lblmodel.setText("Model :");

        lblmodel1.setBackground(new java.awt.Color(255, 255, 255));
        lblmodel1.setForeground(new java.awt.Color(255, 255, 255));
        lblmodel1.setText("Year :");

        lblno.setBackground(new java.awt.Color(255, 255, 255));
        lblno.setForeground(new java.awt.Color(255, 255, 255));
        lblno.setText("Number :");

        lblveviclename.setBackground(new java.awt.Color(255, 255, 255));
        lblveviclename.setForeground(new java.awt.Color(255, 255, 255));
        lblveviclename.setText("Name :");

        txtvehicle_name.setBackground(new java.awt.Color(255, 206, 108));
        txtvehicle_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvehicle_nameActionPerformed(evt);
            }
        });

        txtmodel.setBackground(new java.awt.Color(255, 206, 108));

        txtyear.setBackground(new java.awt.Color(255, 206, 108));

        txtnumber.setBackground(new java.awt.Color(255, 206, 108));

        lblregno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblregno.setForeground(new java.awt.Color(255, 255, 255));
        lblregno.setText("Reg. No :");

        txtreg_no.setBackground(new java.awt.Color(255, 206, 108));
        txtreg_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreg_noActionPerformed(evt);
            }
        });

        lblseats.setBackground(new java.awt.Color(255, 255, 255));
        lblseats.setForeground(new java.awt.Color(255, 255, 255));
        lblseats.setText("Seats :");

        txtseats.setBackground(new java.awt.Color(255, 206, 108));

        lbltype.setBackground(new java.awt.Color(255, 255, 255));
        lbltype.setForeground(new java.awt.Color(255, 255, 255));
        lbltype.setText("Type :");

        jComboBox1.setBackground(new java.awt.Color(255, 206, 108));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A/C", "Non A/c" }));

        javax.swing.GroupLayout pnlvehicle_details1Layout = new javax.swing.GroupLayout(pnlvehicle_details1);
        pnlvehicle_details1.setLayout(pnlvehicle_details1Layout);
        pnlvehicle_details1Layout.setHorizontalGroup(
            pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblregno, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblveviclename, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                        .addGap(825, 825, 825)
                        .addComponent(txtdriven, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblseats, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbltype, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmodel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtseats, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblno, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtreg_no, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtvehicle_name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlvehicle_details1Layout.setVerticalGroup(
            pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtreg_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblregno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblveviclename)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlvehicle_details1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtvehicle_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblmodel)
                    .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblno))
                .addGap(23, 23, 23)
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmodel1)
                    .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblseats)
                    .addComponent(txtseats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltype, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(7, 7, 7)
                .addComponent(txtdriven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );

        getContentPane().add(pnlvehicle_details1);
        pnlvehicle_details1.setBounds(520, 80, 450, 436);

        btnsearch.setBackground(new java.awt.Color(0, 204, 204));
        btnsearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearch);
        btnsearch.setBounds(580, 20, 78, 29);

        txtcustomer_regno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustomer_regnoActionPerformed(evt);
            }
        });
        getContentPane().add(txtcustomer_regno);
        txtcustomer_regno.setBounds(350, 20, 199, 29);

        lblcustomer_regno.setForeground(new java.awt.Color(255, 255, 255));
        lblcustomer_regno.setText("Customer reg. No");
        getContentPane().add(lblcustomer_regno);
        lblcustomer_regno.setBounds(210, 20, 110, 26);

        btnupdate.setBackground(new java.awt.Color(0, 204, 204));
        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(0, 0, 51));
        btnupdate.setText("Update");
        btnupdate.setPreferredSize(new java.awt.Dimension(73, 23));
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate);
        btnupdate.setBounds(850, 530, 90, 30);

        btndelete.setBackground(new java.awt.Color(0, 204, 204));
        btndelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btndelete.setForeground(new java.awt.Color(0, 0, 51));
        btndelete.setText("Delete");
        btndelete.setPreferredSize(new java.awt.Dimension(73, 23));
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete);
        btndelete.setBounds(740, 530, 75, 30);

        btnback.setBackground(new java.awt.Color(0, 204, 204));
        btnback.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnback.setForeground(new java.awt.Color(0, 0, 51));
        btnback.setText("back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback);
        btnback.setBounds(620, 530, 80, 30);

        lblbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/waves-and-stars-background-powerpoint-template.jpg"))); // NOI18N
        lblbackground.setPreferredSize(new java.awt.Dimension(1025, 625));
        getContentPane().add(lblbackground);
        lblbackground.setBounds(0, 0, 1060, 640);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtreg_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreg_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtreg_noActionPerformed

    private void txtvehicle_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvehicle_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvehicle_nameActionPerformed

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnicActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        
        try
        {
            Statement st=con.createStatement();
            String no=txtcustomer_regno.getText();

            String sql="SELECT * FROM customer_details WHERE customer_regno='"+no+"'";
            ResultSet rs=st.executeQuery(sql);

            if(rs.next()==false)
            {
                JOptionPane.showMessageDialog(null, "Invalid rgister number");
            }
            String name=rs.getString("name");
            txtname.setText(name);

            String address=rs.getString("address");
            txtaddress.setText(address);
            
            

            

            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void txtcustomer_regnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustomer_regnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustomer_regnoActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:

        String no=txtcustomer_regno.getText();

        String name=txtname.getText();
        String nic=txtnic.getText();
        String address=txtaddress.getText();
        String phone=txtphone.getText();
        String regno=txtreg_no.getText();
        String vehicle_name=txtvehicle_name.getText();
        String model=txtmodel.getText();
        String year=txtyear.getText();
        String number=txtnumber.getText();
        

        String sql="UPDATE owner_details SET owner_name=?,nic=?,address=?,phone=?,reg_no=?,vehicle_name=?,model=?,year=?,number=?,description=? WHERE reg_no='"+no+"'";
        try
        {
            pst=con.prepareStatement(sql);
            pst.setString(1,txtname.getText());
            pst.setString(2,txtaddress.getText());
            pst.setString(3,txtaddress.getText());
            pst.setString(4,txtphone.getText());
            pst.setString(5,txtreg_no.getText());
            pst.setString(6,txtvehicle_name.getText());
            pst.setString(7,txtmodel.getText());
            pst.setString(8,txtyear.getText());
            pst.setString(9,txtnumber.getText());
    

            pst.execute();
            JOptionPane.showMessageDialog(null, "Successfuly update");

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnbackActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
         String no=txtcustomer_regno.getText();

            String sql="SELECT * FROM customer_details WHERE customer_regno='"+no+"'";
            try
        {
            pst=con.prepareStatement(sql);
            
            pst.executeQuery();
          JOptionPane.showMessageDialog(null, "Successfuly deleted");

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
            
           // try{
              //  txtcustomer_regno.removeAll();
                
               // Statement st=con.createStatement();
                
               // String sql2 = "select * from customer_details";
               // ResultSet rs= st.executeQuery(sql2);
                
             //   while(rs.next())
             //   {
              //     txtcustomer_regno.getText();
            //    }
          //  }
         //   catch(Exception e)
       // {
         //   JOptionPane.showMessageDialog(null, e);
      //  }

           
        
    }//GEN-LAST:event_btndeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer_search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnpackeges;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbladress;
    private javax.swing.JLabel lblbackground;
    private javax.swing.JLabel lblcustomer_details;
    private javax.swing.JLabel lblcustomer_regno;
    private javax.swing.JLabel lbldeposit1;
    private javax.swing.JLabel lbldeposit2;
    private javax.swing.JLabel lblmodel;
    private javax.swing.JLabel lblmodel1;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblnic;
    private javax.swing.JLabel lblno;
    private javax.swing.JLabel lblpackege;
    private javax.swing.JLabel lblpayment;
    private javax.swing.JLabel lblphone;
    private javax.swing.JLabel lblpickup_date;
    private javax.swing.JLabel lblpickup_date1;
    private javax.swing.JLabel lblregno;
    private javax.swing.JLabel lblseats;
    private javax.swing.JLabel lbltype;
    private javax.swing.JLabel lblveviclename;
    private javax.swing.JPanel pnlowner_details;
    private javax.swing.JPanel pnlvehicle_details1;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtcustomer_regno;
    private javax.swing.JTextField txtdriven;
    private javax.swing.JTextField txtmodel;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txtnumber;
    private javax.swing.JTextField txtpackege;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtpickup_time2;
    private javax.swing.JTextField txtpickup_time3;
    private javax.swing.JTextField txtreg_no;
    private javax.swing.JTextField txtseats;
    private javax.swing.JTextField txtvehicle_name;
    private javax.swing.JTextField txtyear;
    // End of variables declaration//GEN-END:variables
}
