/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author USER
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbldisplay = new javax.swing.JLabel();
        pnldashboard = new javax.swing.JPanel();
        btnowner = new javax.swing.JButton();
        btnvehicle = new javax.swing.JButton();
        btnbill = new javax.swing.JButton();
        btncustomer = new javax.swing.JButton();
        btnuser_registration = new javax.swing.JButton();
        lblbill = new javax.swing.JLabel();
        lblvehi_details = new javax.swing.JLabel();
        lbluser_reg = new javax.swing.JLabel();
        lblcust_details = new javax.swing.JLabel();
        btnlogout1 = new javax.swing.JButton();
        lblbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 440));
        setResizable(false);
        getContentPane().setLayout(null);

        lbldisplay.setFont(new java.awt.Font("Stencil", 2, 36)); // NOI18N
        lbldisplay.setForeground(new java.awt.Color(102, 255, 255));
        lbldisplay.setText("VEhicle Rental System");
        getContentPane().add(lbldisplay);
        lbldisplay.setBounds(130, 30, 450, 50);

        pnldashboard.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        pnldashboard.setOpaque(false);

        btnowner.setText("Owner");
        btnowner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnowner.setPreferredSize(new java.awt.Dimension(75, 75));
        btnowner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnownerActionPerformed(evt);
            }
        });

        btnvehicle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vehicle_icon.png"))); // NOI18N
        btnvehicle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnvehicle.setFocusCycleRoot(true);
        btnvehicle.setPreferredSize(new java.awt.Dimension(75, 75));
        btnvehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvehicleActionPerformed(evt);
            }
        });

        btnbill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bill_icon.png"))); // NOI18N
        btnbill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbill.setPreferredSize(new java.awt.Dimension(75, 75));
        btnbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbillActionPerformed(evt);
            }
        });

        btncustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customer_icon.png"))); // NOI18N
        btncustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncustomer.setPreferredSize(new java.awt.Dimension(75, 75));
        btncustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncustomerActionPerformed(evt);
            }
        });

        btnuser_registration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        btnuser_registration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnuser_registration.setPreferredSize(new java.awt.Dimension(75, 75));
        btnuser_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuser_registrationActionPerformed(evt);
            }
        });

        lblbill.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblbill.setForeground(new java.awt.Color(204, 255, 204));
        lblbill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbill.setText("Bill");

        lblvehi_details.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblvehi_details.setForeground(new java.awt.Color(204, 255, 204));
        lblvehi_details.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblvehi_details.setText("Vehicle Details");

        lbluser_reg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbluser_reg.setForeground(new java.awt.Color(204, 255, 204));
        lbluser_reg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbluser_reg.setText("User Registration");

        lblcust_details.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcust_details.setForeground(new java.awt.Color(204, 255, 204));
        lblcust_details.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcust_details.setText("Customer details");

        btnlogout1.setText("Logout");
        btnlogout1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogout1.setPreferredSize(new java.awt.Dimension(75, 75));
        btnlogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogout1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnldashboardLayout = new javax.swing.GroupLayout(pnldashboard);
        pnldashboard.setLayout(pnldashboardLayout);
        pnldashboardLayout.setHorizontalGroup(
            pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldashboardLayout.createSequentialGroup()
                .addGroup(pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnldashboardLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnbill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblbill, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnuser_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addComponent(btnvehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnldashboardLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblcust_details)
                            .addGroup(pnldashboardLayout.createSequentialGroup()
                                .addComponent(lbluser_reg)
                                .addGap(47, 47, 47)
                                .addGroup(pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnldashboardLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(btncustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblvehi_details, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(43, 43, 43)
                .addGroup(pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnowner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlogout1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        pnldashboardLayout.setVerticalGroup(
            pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnldashboardLayout.createSequentialGroup()
                        .addComponent(btnbill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblbill))
                    .addGroup(pnldashboardLayout.createSequentialGroup()
                        .addGroup(pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnvehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnlogout1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblvehi_details)))
                .addGroup(pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnldashboardLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btncustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnowner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcust_details))
                    .addGroup(pnldashboardLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnuser_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbluser_reg)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(pnldashboard);
        pnldashboard.setBounds(50, 110, 600, 270);

        lblbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginpage.jpg"))); // NOI18N
        getContentPane().add(lblbackground);
        lblbackground.setBounds(0, -70, 1380, 530);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncustomerActionPerformed
        // TODO add your handling code here:
        new customer_details().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncustomerActionPerformed

    private void btnownerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnownerActionPerformed
        // TODO add your handling code here:

        new vehicle_search().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnownerActionPerformed

    private void btnuser_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuser_registrationActionPerformed
        // TODO add your handling code here:
        new user_registration().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnuser_registrationActionPerformed

    private void btnvehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvehicleActionPerformed

        new Vehicle_details().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnvehicleActionPerformed

    private void btnbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbillActionPerformed

    private void btnlogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogout1ActionPerformed
        // TODO add your handling code here:
         new home_page().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlogout1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbill;
    private javax.swing.JButton btncustomer;
    private javax.swing.JButton btnlogout1;
    private javax.swing.JButton btnowner;
    private javax.swing.JButton btnuser_registration;
    private javax.swing.JButton btnvehicle;
    private javax.swing.JLabel lblbackground;
    private javax.swing.JLabel lblbill;
    private javax.swing.JLabel lblcust_details;
    private javax.swing.JLabel lbldisplay;
    private javax.swing.JLabel lbluser_reg;
    private javax.swing.JLabel lblvehi_details;
    private javax.swing.JPanel pnldashboard;
    // End of variables declaration//GEN-END:variables
}
