import java.sql.*;
import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author USER
 */
public class home_page extends javax.swing.JFrame {
    Connection con;
    PreparedStatement pst;

    /**
     * Creates new form home_page
     */
    public home_page() {
        
        initComponents();
        con=SQLCON.connect();
        
       
        lblname.setVisible(true);
        lblpassword.setVisible(true);
        txtname.setVisible(true);
        psfpassword.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbldisplay = new javax.swing.JLabel();
        pnllogin = new javax.swing.JPanel();
        psfpassword = new javax.swing.JPasswordField();
        btnexit = new javax.swing.JButton();
        lblpassword = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lblname = new javax.swing.JLabel();
        btnlogin = new javax.swing.JButton();
        lblbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(695, 460));
        setResizable(false);
        getContentPane().setLayout(null);

        lbldisplay.setFont(new java.awt.Font("Stencil", 2, 36)); // NOI18N
        lbldisplay.setForeground(new java.awt.Color(102, 255, 255));
        lbldisplay.setText("VEhicle Rental System");
        getContentPane().add(lbldisplay);
        lbldisplay.setBounds(120, 30, 450, 50);

        pnllogin.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(51, 51, 51)));
        pnllogin.setOpaque(false);

        psfpassword.setBackground(new java.awt.Color(204, 204, 255));
        psfpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psfpasswordActionPerformed(evt);
            }
        });

        btnexit.setBackground(new java.awt.Color(0, 153, 153));
        btnexit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        lblpassword.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        lblpassword.setForeground(new java.awt.Color(0, 255, 255));
        lblpassword.setText("Password :");

        txtname.setBackground(new java.awt.Color(204, 204, 255));

        lblname.setBackground(new java.awt.Color(255, 255, 255));
        lblname.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        lblname.setForeground(new java.awt.Color(51, 255, 255));
        lblname.setText(" User name : ");

        btnlogin.setBackground(new java.awt.Color(0, 153, 153));
        btnlogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlloginLayout = new javax.swing.GroupLayout(pnllogin);
        pnllogin.setLayout(pnlloginLayout);
        pnlloginLayout.setHorizontalGroup(
            pnlloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlloginLayout.createSequentialGroup()
                .addGroup(pnlloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlloginLayout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addGroup(pnlloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlloginLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(pnlloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlloginLayout.createSequentialGroup()
                                .addComponent(lblpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(psfpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlloginLayout.createSequentialGroup()
                                .addComponent(lblname)
                                .addGap(18, 18, 18)
                                .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        pnlloginLayout.setVerticalGroup(
            pnlloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlloginLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(pnlloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(pnlloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(psfpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnlogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnexit)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(pnllogin);
        pnllogin.setBounds(50, 110, 550, 290);

        lblbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginpage.jpg"))); // NOI18N
        getContentPane().add(lblbackground);
        lblbackground.setBounds(0, -80, 1380, 590);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void psfpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psfpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psfpasswordActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
        
        try {
            String passwrd = psfpassword.getText();
            String username = txtname.getText().trim();
            
            PreparedStatement ps = con.prepareStatement("SELECT *FROM user_login WHERE username=? AND password=?" );
            ps.setString(1, username);
            ps.setString(2, passwrd);
            ResultSet rs = ps.executeQuery();
            
            if (txtname.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "User Name or Passwordd is incorect", "Message", JOptionPane.ERROR_MESSAGE);
                txtname.requestFocus();
                return;}
            
            if (psfpassword.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "password can not be Empty", "Message", JOptionPane.ERROR_MESSAGE);
                psfpassword.requestFocus();
                return;}
            
            
            if (rs.next()) {
                if (rs.getString("password").equals(passwrd) && rs.getString("username").equals(username)) {
                    System.setProperty("username", rs.getString("username"));
                    System.setProperty("userDisplayName", rs.getString("username"));
                     new dashboard().setVisible(true);
                     this.dispose();
                    
                }
                } else {
                    JOptionPane.showMessageDialog(this, "you are not allowed to log in", "Message", JOptionPane.ERROR_MESSAGE);
                    psfpassword.requestFocusInWindow();
                   // psfpassword.selectAll();
                }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
       // btnlogout.setVisible(true);
      //  btnbill.setVisible(true);
      //  btnvehicle.setVisible(true);
      //  btncustomer.setVisible(true);
      //  lblname.setVisible(false);
      //  lblpassword.setVisible(false);
      //  txtname.setVisible(false);
      //  psfpassword.setVisible(false);
      //  btnlogin.setVisible(false);
     //   btnexit.setVisible(false);
     //   pnllogin.setVisible(false);
        
        
        
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel lblbackground;
    private javax.swing.JLabel lbldisplay;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JPanel pnllogin;
    private javax.swing.JPasswordField psfpassword;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
