/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author USER
 */
public class Package extends javax.swing.JFrame {

    /**
     * Creates new form Package
     */
    public Package() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        package2 = new javax.swing.JPanel();
        rdbac = new javax.swing.JRadioButton();
        rdbdriver = new javax.swing.JRadioButton();
        rdbtv = new javax.swing.JRadioButton();
        rdbdvd = new javax.swing.JRadioButton();
        lblimage = new javax.swing.JLabel();
        rdbdcd = new javax.swing.JRadioButton();
        rdbdusb = new javax.swing.JRadioButton();
        lblprice = new javax.swing.JLabel();
        btnadd1 = new javax.swing.JButton();
        package1 = new javax.swing.JPanel();
        rdbac1 = new javax.swing.JRadioButton();
        rdbdriver1 = new javax.swing.JRadioButton();
        rdbtv1 = new javax.swing.JRadioButton();
        rdbdvd1 = new javax.swing.JRadioButton();
        lblimage1 = new javax.swing.JLabel();
        rdbdcd1 = new javax.swing.JRadioButton();
        rdbdusb1 = new javax.swing.JRadioButton();
        lblprice1 = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        lblbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Packeges");
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(null);

        package2.setBackground(new java.awt.Color(143, 143, 232));

        rdbac.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbac.setForeground(new java.awt.Color(0, 102, 0));
        rdbac.setSelected(true);
        rdbac.setText("Non A/C");
        rdbac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdbac.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rdbac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbacActionPerformed(evt);
            }
        });

        rdbdriver.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbdriver.setForeground(new java.awt.Color(0, 102, 0));
        rdbdriver.setSelected(true);
        rdbdriver.setText("Driver ");
        rdbdriver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdbdriver.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rdbdriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbdriverActionPerformed(evt);
            }
        });

        rdbtv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbtv.setForeground(new java.awt.Color(0, 102, 0));
        rdbtv.setText("Tv");
        rdbtv.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        rdbdvd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbdvd.setForeground(new java.awt.Color(0, 102, 0));
        rdbdvd.setText("DVD Player");
        rdbdvd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdbdvd.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image.jpg"))); // NOI18N

        rdbdcd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbdcd.setForeground(new java.awt.Color(0, 102, 0));
        rdbdcd.setText("CD audio system ");
        rdbdcd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdbdcd.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        rdbdusb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbdusb.setForeground(new java.awt.Color(0, 102, 0));
        rdbdusb.setText("iPod/USB compatible");
        rdbdusb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdbdusb.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblprice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblprice.setForeground(new java.awt.Color(204, 0, 0));
        lblprice.setText("RS. 3000/=  for 24hour, one way");

        btnadd1.setBackground(new java.awt.Color(51, 0, 51));
        btnadd1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnadd1.setForeground(new java.awt.Color(255, 255, 255));
        btnadd1.setText("Add");

        javax.swing.GroupLayout package2Layout = new javax.swing.GroupLayout(package2);
        package2.setLayout(package2Layout);
        package2Layout.setHorizontalGroup(
            package2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(package2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(package2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(package2Layout.createSequentialGroup()
                        .addComponent(rdbdcd)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, package2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(package2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, package2Layout.createSequentialGroup()
                        .addComponent(btnadd1)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, package2Layout.createSequentialGroup()
                        .addGroup(package2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rdbdusb, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(package2Layout.createSequentialGroup()
                                .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(package2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdbdriver)
                                    .addComponent(rdbtv)
                                    .addComponent(rdbdvd)
                                    .addComponent(rdbac))))
                        .addGap(38, 38, 38))))
        );
        package2Layout.setVerticalGroup(
            package2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(package2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(package2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(package2Layout.createSequentialGroup()
                        .addComponent(rdbac)
                        .addGap(15, 15, 15)
                        .addComponent(rdbdriver)
                        .addGap(18, 18, 18)
                        .addComponent(rdbtv)
                        .addGap(18, 18, 18)
                        .addComponent(rdbdvd))
                    .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(package2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbdcd)
                    .addComponent(rdbdusb))
                .addGap(18, 18, 18)
                .addComponent(lblprice, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnadd1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(package2);
        package2.setBounds(430, 50, 310, 290);

        package1.setBackground(new java.awt.Color(143, 143, 232));

        rdbac1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbac1.setForeground(new java.awt.Color(0, 102, 0));
        rdbac1.setSelected(true);
        rdbac1.setText("A/C  ");
        rdbac1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdbac1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rdbac1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbac1ActionPerformed(evt);
            }
        });

        rdbdriver1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbdriver1.setForeground(new java.awt.Color(0, 102, 0));
        rdbdriver1.setSelected(true);
        rdbdriver1.setText("Driver ");
        rdbdriver1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdbdriver1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rdbdriver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbdriver1ActionPerformed(evt);
            }
        });

        rdbtv1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbtv1.setForeground(new java.awt.Color(0, 102, 0));
        rdbtv1.setSelected(true);
        rdbtv1.setText("Tv   ");
        rdbtv1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        rdbdvd1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbdvd1.setForeground(new java.awt.Color(0, 102, 0));
        rdbdvd1.setSelected(true);
        rdbdvd1.setText("DVD Player");
        rdbdvd1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdbdvd1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblimage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image.jpg"))); // NOI18N

        rdbdcd1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbdcd1.setForeground(new java.awt.Color(0, 102, 0));
        rdbdcd1.setSelected(true);
        rdbdcd1.setText("CD audio system ");
        rdbdcd1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdbdcd1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        rdbdusb1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbdusb1.setForeground(new java.awt.Color(0, 102, 0));
        rdbdusb1.setSelected(true);
        rdbdusb1.setText("iPod/USB compatible");
        rdbdusb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdbdusb1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblprice1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblprice1.setForeground(new java.awt.Color(204, 0, 0));
        lblprice1.setText("RS. 4000/=  for 24 hour, one way");

        btnadd.setBackground(new java.awt.Color(51, 0, 51));
        btnadd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setText("Add");

        javax.swing.GroupLayout package1Layout = new javax.swing.GroupLayout(package1);
        package1.setLayout(package1Layout);
        package1Layout.setHorizontalGroup(
            package1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(package1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(rdbdcd1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, package1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(package1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(package1Layout.createSequentialGroup()
                        .addComponent(lblimage1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(package1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(package1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(package1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdbtv1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdbdvd1)))
                            .addGroup(package1Layout.createSequentialGroup()
                                .addComponent(rdbac1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(package1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(package1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(package1Layout.createSequentialGroup()
                                .addComponent(rdbdriver1)
                                .addGap(24, 24, 24))
                            .addComponent(rdbdusb1))))
                .addGap(16, 16, 16))
            .addGroup(package1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblprice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, package1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnadd)
                .addGap(25, 25, 25))
        );
        package1Layout.setVerticalGroup(
            package1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(package1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(package1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(package1Layout.createSequentialGroup()
                        .addComponent(rdbac1)
                        .addGap(15, 15, 15)
                        .addComponent(rdbdriver1)
                        .addGap(18, 18, 18)
                        .addComponent(rdbtv1)
                        .addGap(18, 18, 18)
                        .addComponent(rdbdvd1))
                    .addComponent(lblimage1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(package1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbdcd1)
                    .addComponent(rdbdusb1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblprice1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnadd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(package1);
        package1.setBounds(60, 50, 310, 290);

        lblbackground.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/waves-and-stars-background-powerpoint-template.jpg"))); // NOI18N
        getContentPane().add(lblbackground);
        lblbackground.setBounds(-20, 0, 1010, 610);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdbacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbacActionPerformed
        // TODO add your handling code here:
        rdbac.setSelected(true);
    }//GEN-LAST:event_rdbacActionPerformed

    private void rdbdriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbdriverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbdriverActionPerformed

    private void rdbac1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbac1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbac1ActionPerformed

    private void rdbdriver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbdriver1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbdriver1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Package.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Package.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Package.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Package.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Package().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnadd1;
    private javax.swing.JLabel lblbackground;
    private javax.swing.JLabel lblimage;
    private javax.swing.JLabel lblimage1;
    private javax.swing.JLabel lblprice;
    private javax.swing.JLabel lblprice1;
    private javax.swing.JPanel package1;
    private javax.swing.JPanel package2;
    private javax.swing.JRadioButton rdbac;
    private javax.swing.JRadioButton rdbac1;
    private javax.swing.JRadioButton rdbdcd;
    private javax.swing.JRadioButton rdbdcd1;
    private javax.swing.JRadioButton rdbdriver;
    private javax.swing.JRadioButton rdbdriver1;
    private javax.swing.JRadioButton rdbdusb;
    private javax.swing.JRadioButton rdbdusb1;
    private javax.swing.JRadioButton rdbdvd;
    private javax.swing.JRadioButton rdbdvd1;
    private javax.swing.JRadioButton rdbtv;
    private javax.swing.JRadioButton rdbtv1;
    // End of variables declaration//GEN-END:variables
}
