/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author USER
 */
import java.sql.*;
import javax.swing.*;
public class user_registration extends javax.swing.JFrame {

    /**
     * Creates new form user_registration
     */
      Connection con;
    PreparedStatement pst;
    public user_registration() {
        initComponents();
          con=SQLCON.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbldisplay = new javax.swing.JLabel();
        pnluser_details = new javax.swing.JPanel();
        lblname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lblnic = new javax.swing.JLabel();
        txtnic = new javax.swing.JTextField();
        lbladress = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        lblphone = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        btnregister = new javax.swing.JButton();
        lbluser_name = new javax.swing.JLabel();
        txtuser_name = new javax.swing.JTextField();
        lbluser_name1 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        btnback = new javax.swing.JButton();
        lblbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Registration");
        setPreferredSize(new java.awt.Dimension(750, 525));
        getContentPane().setLayout(null);

        lbldisplay.setDisplayedMnemonic('A');
        lbldisplay.setFont(new java.awt.Font("Stencil", 2, 36)); // NOI18N
        lbldisplay.setForeground(new java.awt.Color(102, 255, 255));
        lbldisplay.setText("VEhicle Rental System");
        getContentPane().add(lbldisplay);
        lbldisplay.setBounds(140, 10, 450, 50);

        pnluser_details.setBackground(new java.awt.Color(153, 153, 153));
        pnluser_details.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnluser_details.setOpaque(false);

        lblname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblname.setForeground(new java.awt.Color(255, 255, 255));
        lblname.setText("Name :");

        txtname.setBackground(new java.awt.Color(204, 204, 255));

        lblnic.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblnic.setForeground(new java.awt.Color(255, 255, 255));
        lblnic.setText("NIC :");

        txtnic.setBackground(new java.awt.Color(204, 204, 255));
        txtnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnicActionPerformed(evt);
            }
        });

        lbladress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbladress.setForeground(new java.awt.Color(255, 255, 255));
        lbladress.setText("Adress :");

        txtaddress.setBackground(new java.awt.Color(204, 204, 255));
        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });

        lblphone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblphone.setForeground(new java.awt.Color(255, 255, 255));
        lblphone.setText("Phone NO. :");

        txtphone.setBackground(new java.awt.Color(204, 204, 255));
        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });

        btnregister.setBackground(new java.awt.Color(153, 0, 0));
        btnregister.setForeground(new java.awt.Color(153, 255, 0));
        btnregister.setText("Reister");
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });

        lbluser_name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbluser_name.setForeground(new java.awt.Color(255, 255, 255));
        lbluser_name.setText("User name :");

        txtuser_name.setBackground(new java.awt.Color(204, 204, 255));
        txtuser_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuser_nameActionPerformed(evt);
            }
        });

        lbluser_name1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbluser_name1.setForeground(new java.awt.Color(255, 255, 255));
        lbluser_name1.setText("Password :");

        txtpassword.setBackground(new java.awt.Color(204, 204, 255));
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnluser_detailsLayout = new javax.swing.GroupLayout(pnluser_details);
        pnluser_details.setLayout(pnluser_detailsLayout);
        pnluser_detailsLayout.setHorizontalGroup(
            pnluser_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnluser_detailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnluser_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnluser_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnregister)
                        .addGroup(pnluser_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnluser_detailsLayout.createSequentialGroup()
                                .addComponent(lbladress, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnluser_detailsLayout.createSequentialGroup()
                                .addGroup(pnluser_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblnic, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(pnluser_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnluser_detailsLayout.createSequentialGroup()
                        .addComponent(lblphone, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnluser_detailsLayout.createSequentialGroup()
                        .addComponent(lbluser_name, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtuser_name, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnluser_detailsLayout.createSequentialGroup()
                        .addComponent(lbluser_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        pnluser_detailsLayout.setVerticalGroup(
            pnluser_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnluser_detailsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnluser_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnluser_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnic))
                .addGap(18, 18, 18)
                .addGroup(pnluser_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbladress)
                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnluser_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblphone)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(pnluser_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtuser_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbluser_name))
                .addGap(28, 28, 28)
                .addGroup(pnluser_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbluser_name1)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnregister)
                .addGap(69, 69, 69))
        );

        getContentPane().add(pnluser_details);
        pnluser_details.setBounds(190, 60, 380, 410);

        btnback.setBackground(new java.awt.Color(153, 0, 0));
        btnback.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnback.setForeground(new java.awt.Color(102, 204, 0));
        btnback.setText("back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback);
        btnback.setBounds(20, 420, 90, 44);

        lblbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        getContentPane().add(lblbackground);
        lblbackground.setBounds(0, 0, 850, 490);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnicActionPerformed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
        // TODO add your handling code here:
       
        try
        {

            if (txtnic.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "User nic can not be Empty", "Message", JOptionPane.ERROR_MESSAGE);
                txtnic.requestFocus();
                return;
            }
            
            

            if (txtname.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Name can not be Empty", "Message", JOptionPane.ERROR_MESSAGE);
                txtname.requestFocus();
                return;
            }
            if (txtuser_name.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "User name can not be Empty", "Message", JOptionPane.ERROR_MESSAGE);
                txtuser_name.requestFocus();
                return;
            }
            
            if (txtpassword.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "User name can not be Empty", "Message", JOptionPane.ERROR_MESSAGE);
                txtpassword.requestFocus();
                return;
            }
            String sql="INSERT INTO user_login (name,nic,address,phone,username,password) VALUES (?,?,?,?,?,?)";

            pst=con.prepareStatement(sql);

            pst.setString(1,txtname.getText());
            pst.setString(2,txtnic.getText());
            pst.setString(3,txtaddress.getText());
            pst.setString(4,txtphone.getText());
            pst.setString(5,txtuser_name.getText());
            pst.setString(6,txtpassword.getText());
            pst.execute();

            JOptionPane.showMessageDialog(null,"Successfuly added");

            

        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_btnregisterActionPerformed

    private void txtuser_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuser_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuser_nameActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        new dashboard().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnregister;
    private javax.swing.JLabel lbladress;
    private javax.swing.JLabel lblbackground;
    private javax.swing.JLabel lbldisplay;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblnic;
    private javax.swing.JLabel lblphone;
    private javax.swing.JLabel lbluser_name;
    private javax.swing.JLabel lbluser_name1;
    private javax.swing.JPanel pnluser_details;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtuser_name;
    // End of variables declaration//GEN-END:variables
}
