/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author USER
 */
import controls.Database;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class vehicle_search extends javax.swing.JFrame {
     public int reg_no;
    int reg;
    Connection con;
    PreparedStatement pst;

    /**
     * Creates new form vehicle_search
     */
    public vehicle_search() {
        initComponents();
        con=SQLCON.connect();
        load_owner_table();
        load_cmbreg();
        
        pnlowner_details.setVisible(false);
        btnback2.setVisible(false);
        btnupdate.setVisible(false);
        btnExit.setVisible(false);
        pnlvehicle_details1.setVisible(false);        
        pnltable.setVisible(true);
          
         
    }
    private ArrayList<controls.ListItem> combo(String query, String col_ID, String col_Name) throws Exception {
        ArrayList<controls.ListItem> names = new ArrayList<>();
        Statement stmt = Database.getCon().createStatement();
        ResultSet rset = stmt.executeQuery(query);
        while (rset.next()) {
            controls.ListItem item = new controls.ListItem();
            item.setId(rset.getInt(col_ID));
            item.setName(rset.getString(col_Name));
            names.add(item);
        }
        return names;
    }
    
     private void load_cmbreg() {
    try{
              Statement st=con.createStatement();
              
              String no=txtreg_no.getText();

            String sql="SELECT * FROM vehicle_details ORDER BY vehicle_details.vehi_reg_no DESC ";
            ResultSet rs=st.executeQuery(sql);
            
            while(rs.next())
            {
              cmbvehicle_regno.addItem(rs.getString(1));
            }
        }
        catch (Exception e) {
            e.printStackTrace();
        }
     }
     
     private void selectcmb(){
        
         try {
            controls.ListItem user_type = (controls.ListItem) cmbvehicle_regno.getSelectedItem();
            reg = user_type.getId();
           // load_customer_table(reg);
          //  load_pat_details(reg);
        } catch (Exception ex) {
        }
         
     }
       
    private void load_owner_table() {
     try {
            
            Statement st=con.createStatement();
           
            DefaultTableModel table_model= (DefaultTableModel)tblowner_details.getModel();
         
            String sql="SELECT owner_details.reg_no,owner_details.owner_name,owner_details.nic,owner_details.address,owner_details.phone FROM owner_details  ORDER BY owner_details.reg_no DESC";
           ResultSet rs=st.executeQuery(sql);
            
            table_model.setRowCount(0);
            while (rs.next()) {
                ArrayList arrList = new ArrayList();
                arrList.add(rs.getString("reg_no"));
                arrList.add(rs.getString("owner_name"));
                arrList.add(rs.getString("nic"));
                arrList.add(rs.getString("address"));
                arrList.add(rs.getString("phone"));
                
                
                table_model.addRow(arrList.toArray());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
     }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlowner_details = new javax.swing.JPanel();
        lblowner_details = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lblnic = new javax.swing.JLabel();
        txtnic = new javax.swing.JTextField();
        lbladress = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        lblphone = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        lblregno = new javax.swing.JLabel();
        txtreg_no = new javax.swing.JTextField();
        pnlvehicle_details1 = new javax.swing.JPanel();
        lblmodel = new javax.swing.JLabel();
        lblmodel1 = new javax.swing.JLabel();
        lblno = new javax.swing.JLabel();
        lblveviclename = new javax.swing.JLabel();
        txtvehicle_name = new javax.swing.JTextField();
        txtmodel = new javax.swing.JTextField();
        txtyear = new javax.swing.JTextField();
        txtnumber = new javax.swing.JTextField();
        txtdriven = new javax.swing.JTextField();
        lblseats = new javax.swing.JLabel();
        txtseats = new javax.swing.JTextField();
        lbltype = new javax.swing.JLabel();
        cmbvehicle_regno = new javax.swing.JComboBox();
        txttype = new javax.swing.JTextField();
        lblvehicle_detils = new javax.swing.JLabel();
        lblvehi_reg = new javax.swing.JLabel();
        pnltable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblowner_details = new javax.swing.JTable();
        btnExit = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnback2 = new javax.swing.JButton();
        lbldisplay = new javax.swing.JLabel();
        lblbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(null);

        pnlowner_details.setBackground(new java.awt.Color(204, 204, 255));
        pnlowner_details.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        pnlowner_details.setOpaque(false);

        lblowner_details.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblowner_details.setForeground(new java.awt.Color(204, 204, 255));
        lblowner_details.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblowner_details.setText("About Owner");
        lblowner_details.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblname.setForeground(new java.awt.Color(255, 255, 255));
        lblname.setText("Name :");

        txtname.setBackground(new java.awt.Color(204, 204, 255));

        lblnic.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblnic.setForeground(new java.awt.Color(255, 255, 255));
        lblnic.setText("NIC :");

        txtnic.setBackground(new java.awt.Color(204, 204, 255));
        txtnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnicActionPerformed(evt);
            }
        });

        lbladress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbladress.setForeground(new java.awt.Color(255, 255, 255));
        lbladress.setText("Adress :");

        txtaddress.setBackground(new java.awt.Color(204, 204, 255));
        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });

        lblphone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblphone.setForeground(new java.awt.Color(255, 255, 255));
        lblphone.setText("Phone NO. :");

        txtphone.setBackground(new java.awt.Color(204, 204, 255));
        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });

        lblregno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblregno.setForeground(new java.awt.Color(255, 255, 255));
        lblregno.setText("Vehicle owner Reg. No :");

        txtreg_no.setEditable(false);
        txtreg_no.setBackground(new java.awt.Color(204, 204, 255));
        txtreg_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreg_noActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlowner_detailsLayout = new javax.swing.GroupLayout(pnlowner_details);
        pnlowner_details.setLayout(pnlowner_detailsLayout);
        pnlowner_detailsLayout.setHorizontalGroup(
            pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(lblowner_details, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlowner_detailsLayout.createSequentialGroup()
                                .addComponent(lblnic, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                                .addComponent(lbladress, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                                .addComponent(lblphone, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                                .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblregno, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtreg_no, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        pnlowner_detailsLayout.setVerticalGroup(
            pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblowner_details, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblregno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtreg_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnic)
                    .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtaddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbladress, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(39, 39, 39)
                .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblphone))
                .addGap(115, 115, 115))
        );

        getContentPane().add(pnlowner_details);
        pnlowner_details.setBounds(30, 50, 380, 440);

        pnlvehicle_details1.setBackground(new java.awt.Color(104, 94, 137));
        pnlvehicle_details1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        pnlvehicle_details1.setOpaque(false);

        lblmodel.setBackground(new java.awt.Color(255, 255, 255));
        lblmodel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblmodel.setForeground(new java.awt.Color(255, 255, 255));
        lblmodel.setText("Model :");

        lblmodel1.setBackground(new java.awt.Color(255, 255, 255));
        lblmodel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblmodel1.setForeground(new java.awt.Color(255, 255, 255));
        lblmodel1.setText("Year :");

        lblno.setBackground(new java.awt.Color(255, 255, 255));
        lblno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblno.setForeground(new java.awt.Color(255, 255, 255));
        lblno.setText("Number :");

        lblveviclename.setBackground(new java.awt.Color(255, 255, 255));
        lblveviclename.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblveviclename.setForeground(new java.awt.Color(255, 255, 255));
        lblveviclename.setText("Name :");

        txtvehicle_name.setBackground(new java.awt.Color(204, 204, 255));
        txtvehicle_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvehicle_nameActionPerformed(evt);
            }
        });

        txtmodel.setBackground(new java.awt.Color(204, 204, 255));

        txtyear.setBackground(new java.awt.Color(204, 204, 255));

        txtnumber.setBackground(new java.awt.Color(204, 204, 255));
        txtnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumberActionPerformed(evt);
            }
        });

        lblseats.setBackground(new java.awt.Color(255, 255, 255));
        lblseats.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblseats.setForeground(new java.awt.Color(255, 255, 255));
        lblseats.setText("Seats :");

        txtseats.setBackground(new java.awt.Color(204, 204, 255));

        lbltype.setBackground(new java.awt.Color(255, 255, 255));
        lbltype.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltype.setForeground(new java.awt.Color(255, 255, 255));
        lbltype.setText("Type :");

        cmbvehicle_regno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbvehicle_regnoItemStateChanged(evt);
            }
        });
        cmbvehicle_regno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbvehicle_regnoActionPerformed(evt);
            }
        });

        txttype.setBackground(new java.awt.Color(204, 204, 255));

        lblvehicle_detils.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblvehicle_detils.setForeground(new java.awt.Color(255, 255, 255));
        lblvehicle_detils.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblvehicle_detils.setText("Vehicle Details");

        lblvehi_reg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblvehi_reg.setForeground(new java.awt.Color(255, 255, 255));
        lblvehi_reg.setText("Vehicle Reg.NO :");

        javax.swing.GroupLayout pnlvehicle_details1Layout = new javax.swing.GroupLayout(pnlvehicle_details1);
        pnlvehicle_details1.setLayout(pnlvehicle_details1Layout);
        pnlvehicle_details1Layout.setHorizontalGroup(
            pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblseats, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmodel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbltype, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblno, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblveviclename, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblvehi_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtvehicle_name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttype, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                                .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(615, 615, 615)
                                .addComponent(txtdriven, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbvehicle_regno, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtseats, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(lblvehicle_detils, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlvehicle_details1Layout.setVerticalGroup(
            pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblvehicle_detils)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbvehicle_regno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblvehi_reg))
                .addGap(18, 18, 18)
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlvehicle_details1Layout.createSequentialGroup()
                        .addComponent(txtvehicle_name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlvehicle_details1Layout.createSequentialGroup()
                        .addComponent(lblveviclename)
                        .addGap(18, 18, 18)
                        .addComponent(lblmodel)))
                .addGap(10, 10, 10)
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblno)
                    .addComponent(txtnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                        .addComponent(txtdriven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlvehicle_details1Layout.createSequentialGroup()
                        .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmodel1))
                        .addGap(18, 18, 18)))
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtseats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblseats))
                .addGap(18, 18, 18)
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltype)
                    .addComponent(txttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110))
        );

        getContentPane().add(pnlvehicle_details1);
        pnlvehicle_details1.setBounds(450, 50, 450, 436);

        pnltable.setBackground(new java.awt.Color(153, 153, 153));
        pnltable.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        pnltable.setOpaque(false);

        tblowner_details.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "reg_no", "owner_name", "nic", "address", "phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblowner_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblowner_detailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblowner_details);
        if (tblowner_details.getColumnModel().getColumnCount() > 0) {
            tblowner_details.getColumnModel().getColumn(0).setResizable(false);
            tblowner_details.getColumnModel().getColumn(1).setResizable(false);
            tblowner_details.getColumnModel().getColumn(2).setResizable(false);
            tblowner_details.getColumnModel().getColumn(3).setResizable(false);
            tblowner_details.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout pnltableLayout = new javax.swing.GroupLayout(pnltable);
        pnltable.setLayout(pnltableLayout);
        pnltableLayout.setHorizontalGroup(
            pnltableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnltableLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        pnltableLayout.setVerticalGroup(
            pnltableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltableLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        getContentPane().add(pnltable);
        pnltable.setBounds(120, 90, 700, 360);

        btnExit.setBackground(new java.awt.Color(153, 0, 0));
        btnExit.setForeground(new java.awt.Color(153, 255, 0));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(690, 520, 70, 23);

        btnupdate.setBackground(new java.awt.Color(153, 0, 0));
        btnupdate.setForeground(new java.awt.Color(153, 255, 0));
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate);
        btnupdate.setBounds(580, 520, 90, 23);

        btnback2.setBackground(new java.awt.Color(153, 0, 0));
        btnback2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnback2.setForeground(new java.awt.Color(153, 255, 0));
        btnback2.setText("back");
        btnback2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnback2);
        btnback2.setBounds(490, 520, 70, 22);

        lbldisplay.setFont(new java.awt.Font("Stencil", 2, 36)); // NOI18N
        lbldisplay.setForeground(new java.awt.Color(102, 255, 255));
        lbldisplay.setText("VEhicle Rental System");
        getContentPane().add(lbldisplay);
        lbldisplay.setBounds(260, 10, 450, 50);

        lblbackground.setBackground(new java.awt.Color(99, 3, 46));
        lblbackground.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblbackground.setForeground(new java.awt.Color(204, 204, 255));
        lblbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        lblbackground.setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().add(lblbackground);
        lblbackground.setBounds(0, 0, 1000, 560);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnicActionPerformed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void txtvehicle_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvehicle_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvehicle_nameActionPerformed

    private void txtnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumberActionPerformed

    private void txtreg_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreg_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtreg_noActionPerformed

    private void cmbvehicle_regnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbvehicle_regnoItemStateChanged
        // TODO add your handling code here:
      selectcmb();
            
         /* try{
              
           Statement st1=con.createStatement();
           String reg=cmbvehicle_regno.getSelectedItem().toString();

            String sql2="SELECT * FROM vehicle_details WHERE vehi_reg_no='"+reg+"'";
            ResultSet res=st1.executeQuery(sql2);

            if(res.next()==false)
            {
                JOptionPane.showMessageDialog(null, "Inavalid  vehicle registr number");
            }
            String name1=res.getString("name");
            txtvehicle_name.setText(name1);

            String model=res.getString("model");
            txtmodel.setText(model);
            
             int year =res.getInt("year");
            txtyear.setText(String.valueOf(year));
            
            
            String number=res.getString("number");
            txtnumber.setText(number);
            
            String seats=res.getString("seats");
            txtseats.setText(seats);
            
            String type=res.getString("type");
            txttype.setText(type);
            
            
           
            
            
       } 
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }*/

    }//GEN-LAST:event_cmbvehicle_regnoItemStateChanged

    private void cmbvehicle_regnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbvehicle_regnoActionPerformed
        // TODO add your handling code here:
       try{
              
           Statement st1=con.createStatement();
           String reg=cmbvehicle_regno.getSelectedItem().toString();

            String sql2="SELECT * FROM vehicle_details WHERE vehi_reg_no='"+reg+"'";
            ResultSet res=st1.executeQuery(sql2);

            if(res.next()==false)
            {
                JOptionPane.showMessageDialog(null, "Inavalid  vehicle registr number");
            }
            String name1=res.getString("name");
            txtvehicle_name.setText(name1);

            String model=res.getString("model");
            txtmodel.setText(model);
            
             int year =res.getInt("year");
            txtyear.setText(String.valueOf(year));
            
            
            String number=res.getString("number");
            txtnumber.setText(number);
            
            String seats=res.getString("seats");
            txtseats.setText(seats);
            
            String type=res.getString("type");
            txttype.setText(type);
            
            
           
            
            
       } 
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_cmbvehicle_regnoActionPerformed

    private void tblowner_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblowner_detailsMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
        pnlowner_details.setVisible(true);
        pnlvehicle_details1.setVisible(true);
        btnupdate.setVisible(true);
        btnback2.setVisible(true);
        btnupdate.setVisible(true);
        btnExit.setVisible(true);        
        pnltable.setVisible(false);
       
       
        //cust_regno = Integer.valueOf(tblcustomer_details.getValueAt(tblcustomer_details.getSelectedRow(), 0).toString());
       reg_no = Integer.valueOf(tblowner_details.getValueAt(tblowner_details.getSelectedRow(), 0).toString());
       txtreg_no.setText(String.valueOf(reg_no ));
       txtname.requestFocus();
       
       try
        {
            Statement st=con.createStatement();
            String no=txtreg_no.getText();

            String sql="SELECT * FROM owner_details WHERE reg_no='"+no+"'";
            ResultSet rs=st.executeQuery(sql);

            if(rs.next()==false)
            {
                JOptionPane.showMessageDialog(null, "Invalid rgister number");
            }
            String name=rs.getString("owner_name");
            txtname.setText(name);

            String address=rs.getString("address");
            txtaddress.setText(address);
            
             String nic=rs.getString("nic");
            txtnic.setText(nic);
            
            int phone =rs.getInt("phone");
            txtphone.setText(String.valueOf(phone));

            
            
         
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
       
        
    
        }
    }//GEN-LAST:event_tblowner_detailsMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
       
        String reg=txtreg_no.getText();
        String name=txtname.getText();
        String address=txtaddress.getText();
        String nic=txtnic.getText();
        String phone=txtphone.getText();
        
        String sql="UPDATE owner_details SET reg_no=?,owner_name=?,address=?,phone=?,nic=? WHERE rg_no='"+reg+"'";

        try{
            pst=con.prepareStatement(sql);
            pst.setString(1,txtreg_no.getText());
            pst.setString(2,txtname.getText());
            pst.setString(3,txtaddress.getText());
            pst.setString(4,txtphone.getText());
            pst.setString(5,txtnic.getText());

        }

        catch (Exception e) {

            JOptionPane.showMessageDialog(null,"succssesffful");
        }

    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnback2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback2ActionPerformed
        // TODO add your handling code here:

        pnlowner_details.setVisible(false);
        pnlvehicle_details1.setVisible(false);
        pnltable.setVisible(true);
        btnupdate.setVisible(false);
        btnExit.setVisible(false);
        btnback2.setVisible(false);
        
    }//GEN-LAST:event_btnback2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vehicle_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vehicle_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vehicle_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vehicle_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vehicle_search().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnback2;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox cmbvehicle_regno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbladress;
    private javax.swing.JLabel lblbackground;
    private javax.swing.JLabel lbldisplay;
    private javax.swing.JLabel lblmodel;
    private javax.swing.JLabel lblmodel1;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblnic;
    private javax.swing.JLabel lblno;
    private javax.swing.JLabel lblowner_details;
    private javax.swing.JLabel lblphone;
    private javax.swing.JLabel lblregno;
    private javax.swing.JLabel lblseats;
    private javax.swing.JLabel lbltype;
    private javax.swing.JLabel lblvehi_reg;
    private javax.swing.JLabel lblvehicle_detils;
    private javax.swing.JLabel lblveviclename;
    private javax.swing.JPanel pnlowner_details;
    private javax.swing.JPanel pnltable;
    private javax.swing.JPanel pnlvehicle_details1;
    private javax.swing.JTable tblowner_details;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtdriven;
    private javax.swing.JTextField txtmodel;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txtnumber;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtreg_no;
    private javax.swing.JTextField txtseats;
    private javax.swing.JTextField txttype;
    private javax.swing.JTextField txtvehicle_name;
    private javax.swing.JTextField txtyear;
    // End of variables declaration//GEN-END:variables
}
