import java.sql.*;
import javax.swing.*;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author USER
 */

public class Vehicle_details extends javax.swing.JFrame {

    public int ve_id = 1;
    public int v_id = 0;
    /**
     * Creates new form vehicle_delete
     */
     public int vehi_reg_no;
        Connection con;
        PreparedStatement pst;
    public Vehicle_details() {
        
         initComponents();
         con=SQLCON.connect();
         
        pnlcustomer_deitails1.setVisible(false);
        pnlvehicle_details1.setVisible(false);
        tblvehicle_details.setVisible(true);
        btnadd.setVisible(true);
        btnadd1.setVisible(false);
        pnlcustomer_details.setVisible(true);
        btnback1.setVisible(false);
        load_vehicle_table();
          
          
    }
    
  
    
    private void load_vehicle_table() {
        
            try {                
            
            Statement st=con.createStatement();
            int stes=0;
            DefaultTableModel table_model= (DefaultTableModel)tblvehicle_details.getModel();
         
            String sql="SELECT vehicle_details.vehi_reg_no,vehicle_details.name,vehicle_details.model,vehicle_details.year,vehicle_details.number,vehicle_details.seats,vehicle_details.type FROM vehicle_details  WHERE vehicle_details.states='"+stes+"' ORDER BY vehicle_details.vehi_reg_no DESC";
            ResultSet rs=st.executeQuery(sql);
            
            table_model.setRowCount(0);
            while (rs.next()) {
                ArrayList arrList = new ArrayList();
                arrList.add(rs.getString("vehi_reg_no"));
                arrList.add(rs.getString("name"));
                arrList.add(rs.getString("model"));
                arrList.add(rs.getString("year"));
                arrList.add(rs.getString("number"));
                arrList.add(rs.getString("seats"));
                arrList.add(rs.getString("type"));                
               
                table_model.addRow(arrList.toArray());
                            }
                    } 
            
            catch (Exception e) 
            {
            e.printStackTrace();
            }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnldetails = new javax.swing.JPanel();
        btnadd1 = new javax.swing.JButton();
        btnback1 = new javax.swing.JButton();
        pnlvehicle_details1 = new javax.swing.JPanel();
        lblmodel = new javax.swing.JLabel();
        lblmodel1 = new javax.swing.JLabel();
        lblno = new javax.swing.JLabel();
        lblveviclename = new javax.swing.JLabel();
        txtvehicle_name = new javax.swing.JTextField();
        txtmodel = new javax.swing.JTextField();
        txtyear = new javax.swing.JTextField();
        txtnumber = new javax.swing.JTextField();
        lblregno = new javax.swing.JLabel();
        txtreg_no = new javax.swing.JTextField();
        txtdriven = new javax.swing.JTextField();
        lblseats = new javax.swing.JLabel();
        txtseats = new javax.swing.JTextField();
        lbltype = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        lblvehicle_detils = new javax.swing.JLabel();
        lblvehicle_detils1 = new javax.swing.JLabel();
        pnlcustomer_deitails1 = new javax.swing.JPanel();
        lblcustomer_details = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lblnic = new javax.swing.JLabel();
        lbladress = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        lblphone = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        txtrented_date = new javax.swing.JTextField();
        txtreleas_date = new javax.swing.JTextField();
        txtnic = new javax.swing.JTextField();
        lblcustomer_regno = new javax.swing.JLabel();
        txtcustomer_regno = new javax.swing.JTextField();
        lblreted_date = new javax.swing.JLabel();
        lblreleas_date1 = new javax.swing.JLabel();
        pnlcustomer_details = new javax.swing.JPanel();
        btnadd = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblvehicle_details = new javax.swing.JTable();
        lblavailable = new javax.swing.JLabel();
        lblavailable1 = new javax.swing.JLabel();
        lbldisplay = new javax.swing.JLabel();
        lblbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vehicle Details");
        setPreferredSize(new java.awt.Dimension(1010, 622));
        setResizable(false);
        getContentPane().setLayout(null);

        pnldetails.setOpaque(false);

        btnadd1.setBackground(new java.awt.Color(0, 102, 102));
        btnadd1.setText("Add");
        btnadd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd1ActionPerformed(evt);
            }
        });

        btnback1.setBackground(new java.awt.Color(0, 102, 102));
        btnback1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnback1.setForeground(new java.awt.Color(255, 255, 255));
        btnback1.setText("back");
        btnback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback1ActionPerformed(evt);
            }
        });

        pnlvehicle_details1.setBackground(new java.awt.Color(104, 94, 137));
        pnlvehicle_details1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        pnlvehicle_details1.setOpaque(false);

        lblmodel.setBackground(new java.awt.Color(255, 255, 255));
        lblmodel.setForeground(new java.awt.Color(255, 255, 255));
        lblmodel.setText("Model :");

        lblmodel1.setBackground(new java.awt.Color(255, 255, 255));
        lblmodel1.setForeground(new java.awt.Color(255, 255, 255));
        lblmodel1.setText("Year :");

        lblno.setBackground(new java.awt.Color(255, 255, 255));
        lblno.setForeground(new java.awt.Color(255, 255, 255));
        lblno.setText("Number :");

        lblveviclename.setBackground(new java.awt.Color(255, 255, 255));
        lblveviclename.setForeground(new java.awt.Color(255, 255, 255));
        lblveviclename.setText("Name :");

        txtvehicle_name.setBackground(new java.awt.Color(204, 204, 255));
        txtvehicle_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvehicle_nameActionPerformed(evt);
            }
        });

        txtmodel.setBackground(new java.awt.Color(204, 204, 255));

        txtyear.setBackground(new java.awt.Color(204, 204, 255));
        txtyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtyearActionPerformed(evt);
            }
        });

        txtnumber.setBackground(new java.awt.Color(204, 204, 255));

        lblregno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblregno.setForeground(new java.awt.Color(255, 255, 255));
        lblregno.setText("Reg. No :");

        txtreg_no.setBackground(new java.awt.Color(204, 204, 255));
        txtreg_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreg_noActionPerformed(evt);
            }
        });

        lblseats.setBackground(new java.awt.Color(255, 255, 255));
        lblseats.setForeground(new java.awt.Color(255, 255, 255));
        lblseats.setText("Seats :");

        txtseats.setBackground(new java.awt.Color(204, 204, 255));

        lbltype.setBackground(new java.awt.Color(255, 255, 255));
        lbltype.setForeground(new java.awt.Color(255, 255, 255));
        lbltype.setText("Type :");

        jComboBox1.setBackground(new java.awt.Color(255, 206, 108));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A/C", "Non A/c" }));

        lblvehicle_detils.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblvehicle_detils.setForeground(new java.awt.Color(255, 255, 255));
        lblvehicle_detils.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblvehicle_detils.setText("Vehicle Details");

        lblvehicle_detils1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblvehicle_detils1.setForeground(new java.awt.Color(204, 204, 255));
        lblvehicle_detils1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblvehicle_detils1.setText("Vehicle Details");

        javax.swing.GroupLayout pnlvehicle_details1Layout = new javax.swing.GroupLayout(pnlvehicle_details1);
        pnlvehicle_details1.setLayout(pnlvehicle_details1Layout);
        pnlvehicle_details1Layout.setHorizontalGroup(
            pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                        .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblseats, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbltype, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblregno, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblveviclename, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblno, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmodel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                                .addGap(734, 734, 734)
                                .addComponent(txtdriven, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtseats, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtvehicle_name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtreg_no, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                        .addComponent(lblvehicle_detils, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(681, 681, 681)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                    .addGap(375, 375, 375)
                    .addComponent(lblvehicle_detils1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(399, Short.MAX_VALUE)))
        );
        pnlvehicle_details1Layout.setVerticalGroup(
            pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlvehicle_details1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblvehicle_detils)
                .addGap(35, 35, 35)
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtreg_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblregno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtvehicle_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblveviclename))
                .addGap(28, 28, 28)
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmodel))
                .addGap(18, 18, 18)
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblno)
                    .addComponent(txtnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmodel1)
                    .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                        .addComponent(lblseats)
                        .addGap(24, 24, 24)
                        .addComponent(txtdriven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                        .addComponent(txtseats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbltype))))
                .addGap(79, 79, 79))
            .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                    .addGap(201, 201, 201)
                    .addComponent(lblvehicle_detils1)
                    .addContainerGap(202, Short.MAX_VALUE)))
        );

        pnlcustomer_deitails1.setBackground(new java.awt.Color(104, 94, 137));
        pnlcustomer_deitails1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        pnlcustomer_deitails1.setOpaque(false);

        lblcustomer_details.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblcustomer_details.setForeground(new java.awt.Color(204, 204, 255));
        lblcustomer_details.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcustomer_details.setText("Coustomer details");
        lblcustomer_details.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblname.setForeground(new java.awt.Color(255, 255, 255));
        lblname.setText("Name :");

        txtname.setBackground(new java.awt.Color(204, 204, 255));

        lblnic.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblnic.setForeground(new java.awt.Color(255, 255, 255));
        lblnic.setText("NIC :");

        lbladress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbladress.setForeground(new java.awt.Color(255, 255, 255));
        lbladress.setText("Adress :");

        txtaddress.setBackground(new java.awt.Color(204, 204, 255));
        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });

        lblphone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblphone.setForeground(new java.awt.Color(255, 255, 255));
        lblphone.setText("Phone NO. :");

        txtphone.setBackground(new java.awt.Color(204, 204, 255));
        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });

        txtrented_date.setBackground(new java.awt.Color(204, 204, 255));

        txtreleas_date.setBackground(new java.awt.Color(204, 204, 255));

        txtnic.setBackground(new java.awt.Color(204, 204, 255));
        txtnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnicActionPerformed(evt);
            }
        });

        lblcustomer_regno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcustomer_regno.setForeground(new java.awt.Color(255, 255, 255));
        lblcustomer_regno.setText("Customer Reg No :");

        txtcustomer_regno.setBackground(new java.awt.Color(204, 204, 255));

        lblreted_date.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblreted_date.setForeground(new java.awt.Color(255, 255, 255));
        lblreted_date.setText("Rented date :");

        lblreleas_date1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblreleas_date1.setForeground(new java.awt.Color(255, 255, 255));
        lblreleas_date1.setText("Releas date :");

        javax.swing.GroupLayout pnlcustomer_deitails1Layout = new javax.swing.GroupLayout(pnlcustomer_deitails1);
        pnlcustomer_deitails1.setLayout(pnlcustomer_deitails1Layout);
        pnlcustomer_deitails1Layout.setHorizontalGroup(
            pnlcustomer_deitails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlcustomer_deitails1Layout.createSequentialGroup()
                .addGroup(pnlcustomer_deitails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlcustomer_deitails1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lblcustomer_details, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlcustomer_deitails1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(pnlcustomer_deitails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblnic, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbladress, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblphone, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblreted_date)
                            .addComponent(lblreleas_date1)
                            .addComponent(lblcustomer_regno))
                        .addGroup(pnlcustomer_deitails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlcustomer_deitails1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(pnlcustomer_deitails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcustomer_regno, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtrented_date, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlcustomer_deitails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtnic, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                        .addComponent(txtname)
                                        .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtreleas_date, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlcustomer_deitails1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        pnlcustomer_deitails1Layout.setVerticalGroup(
            pnlcustomer_deitails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlcustomer_deitails1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblcustomer_details)
                .addGap(18, 18, 18)
                .addGroup(pnlcustomer_deitails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcustomer_regno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcustomer_regno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(pnlcustomer_deitails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlcustomer_deitails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnic)
                    .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlcustomer_deitails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbladress))
                .addGap(29, 29, 29)
                .addGroup(pnlcustomer_deitails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblphone)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pnlcustomer_deitails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblreted_date, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtrented_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnlcustomer_deitails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtreleas_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblreleas_date1))
                .addGap(114, 114, 114))
        );

        javax.swing.GroupLayout pnldetailsLayout = new javax.swing.GroupLayout(pnldetails);
        pnldetails.setLayout(pnldetailsLayout);
        pnldetailsLayout.setHorizontalGroup(
            pnldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldetailsLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(pnlcustomer_deitails1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(pnlvehicle_details1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldetailsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnback1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnadd1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        pnldetailsLayout.setVerticalGroup(
            pnldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldetailsLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlcustomer_deitails1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlvehicle_details1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnback1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnadd1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(pnldetails);
        pnldetails.setBounds(30, 20, 930, 550);

        pnlcustomer_details.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        pnlcustomer_details.setOpaque(false);
        pnlcustomer_details.setLayout(null);

        btnadd.setBackground(new java.awt.Color(0, 153, 153));
        btnadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setText("Add NEW");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        pnlcustomer_details.add(btnadd);
        btnadd.setBounds(30, 20, 110, 40);

        btnback.setBackground(new java.awt.Color(0, 153, 153));
        btnback.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        pnlcustomer_details.add(btnback);
        btnback.setBounds(150, 20, 120, 40);

        tblvehicle_details.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "vehicle_reg_no", "naame", "model", "year", "number", "seats", "type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblvehicle_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblvehicle_detailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblvehicle_details);
        if (tblvehicle_details.getColumnModel().getColumnCount() > 0) {
            tblvehicle_details.getColumnModel().getColumn(0).setResizable(false);
            tblvehicle_details.getColumnModel().getColumn(0).setPreferredWidth(95);
            tblvehicle_details.getColumnModel().getColumn(1).setResizable(false);
            tblvehicle_details.getColumnModel().getColumn(2).setResizable(false);
            tblvehicle_details.getColumnModel().getColumn(3).setResizable(false);
            tblvehicle_details.getColumnModel().getColumn(4).setResizable(false);
            tblvehicle_details.getColumnModel().getColumn(5).setResizable(false);
            tblvehicle_details.getColumnModel().getColumn(6).setResizable(false);
        }

        pnlcustomer_details.add(jScrollPane1);
        jScrollPane1.setBounds(110, 200, 668, 220);

        lblavailable.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        lblavailable.setForeground(new java.awt.Color(153, 255, 51));
        lblavailable.setText("Double lick the Vehicle forbooking !\n ");
        pnlcustomer_details.add(lblavailable);
        lblavailable.setBounds(120, 140, 500, 60);

        lblavailable1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblavailable1.setForeground(new java.awt.Color(255, 255, 204));
        lblavailable1.setText("Availabel Vehicles!\n ");
        pnlcustomer_details.add(lblavailable1);
        lblavailable1.setBounds(240, 100, 420, 60);

        getContentPane().add(pnlcustomer_details);
        pnlcustomer_details.setBounds(50, 50, 870, 530);

        lbldisplay.setFont(new java.awt.Font("Stencil", 2, 36)); // NOI18N
        lbldisplay.setForeground(new java.awt.Color(102, 255, 255));
        lbldisplay.setText("VEhicle Rental System");
        getContentPane().add(lbldisplay);
        lbldisplay.setBounds(260, 0, 450, 50);

        lblbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        getContentPane().add(lblbackground);
        lblbackground.setBounds(-1, -6, 1000, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        new vehicle_add().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        new dashboard().setVisible(true);
        this.dispose();
        

    }//GEN-LAST:event_btnbackActionPerformed

    private void tblvehicle_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblvehicle_detailsMouseClicked
        // TODO add your handling code here:
        
        if (evt.getClickCount() == 2) {
            
        pnlcustomer_deitails1.setVisible(true);
        pnlvehicle_details1.setVisible(true);
        tblvehicle_details.setVisible(false);
        pnlcustomer_details.setVisible(false);
        btnadd1.setVisible(true);
        btnback1.setVisible(true);
        btnadd.setVisible(false);
        
       vehi_reg_no= Integer.valueOf(tblvehicle_details.getValueAt(tblvehicle_details.getSelectedRow(), 0).toString());
       txtreg_no.setText(String.valueOf(vehi_reg_no ));
       txtname.requestFocus();
        
       try
        {
            Statement st=con.createStatement();
            String no=txtreg_no.getText();

            String sql="SELECT * FROM vehicle_details WHERE vehi_reg_no='"+no+"'";
            ResultSet rs=st.executeQuery(sql);

            if(rs.next()==false)
            {
                JOptionPane.showMessageDialog(null, "Invalid rgister number");
            }
            int reg =rs.getInt("vehi_reg_no");
           txtreg_no.setText(String.valueOf(reg));
            
            String name=rs.getString("name");
            txtvehicle_name.setText(name);

            String model=rs.getString("model");
            txtmodel.setText(model);
            
             String number=rs.getString("number");
            txtnumber.setText(number);
            
            int year =rs.getInt("year");
            txtyear.setText(String.valueOf(year));

            int seats =rs.getInt("seats");
            txtseats.setText(String.valueOf(seats));      
            
                                  
            }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
            }
    
    }//GEN-LAST:event_tblvehicle_detailsMouseClicked

    private void txtvehicle_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvehicle_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvehicle_nameActionPerformed

    private void txtreg_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreg_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtreg_noActionPerformed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void txtnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnicActionPerformed

    private void btnadd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd1ActionPerformed
        // TODO add your handling code here:
         try {
              if (txtname.getText().trim().isEmpty() &&(txtnic.getText().trim().isEmpty())){
                JOptionPane.showMessageDialog(this, "Register the customer first!", "Message", JOptionPane.ERROR_MESSAGE);
                txtname.requestFocus();
                return;
            }
             
            if (txtname.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Customer Name can not be Empty", "Message", JOptionPane.ERROR_MESSAGE);
                txtname.requestFocus();
                return;
            }
            
             if (txtnic.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Customer NIC can not be Empty", "Message", JOptionPane.ERROR_MESSAGE);
                txtnic.requestFocus();
                return;
            }
             
              if (txtaddress.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Customer address can not be Empty", "Message", JOptionPane.ERROR_MESSAGE);
                txtaddress.requestFocus();
                return;
            }
              
              
              if (txtphone.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Customer phone number can not be Empty", "Message", JOptionPane.ERROR_MESSAGE);
                txtphone.requestFocus();
                return;
            }
              
              
              if (txtrented_date.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "INclude the rented date", "Message", JOptionPane.ERROR_MESSAGE);
                txtrented_date.requestFocus();
                return;
            }
               if (txtreleas_date.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Relese date can not be Empty", "Message", JOptionPane.ERROR_MESSAGE);
                txtreleas_date.requestFocus();
                return;
            }
        
        
        
        String sql="INSERT INTO customer_details (name,nic,address,phone,rented_date,releas_date,vehi_reg_no,states) VALUES (?,?,?,?,?,?,?,?)";
       
        {
            pst=con.prepareStatement(sql);
           
            pst.setString(1,txtname.getText());
            pst.setString(2,txtnic.getText());
            pst.setString(3,txtaddress.getText());
            pst.setString(4,txtphone.getText());     
            pst.setString(5,txtrented_date.getText());
            pst.setString(6,txtreleas_date.getText());          
            pst.setString(7,txtreg_no.getText()); 
            pst.setInt(8, v_id);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Successfuly added");
            
               //int ve_id=1;
         String reg=txtreg_no.getText();
         String sql3="UPDATE vehicle_details SET states=? WHERE vehi_reg_no='"+reg+"'";
         try
         {
            pst=con.prepareStatement(sql3);
             pst.setInt(1, ve_id);
             pst.execute();
              JOptionPane.showMessageDialog(null,"Succsessfull");
             
         }
          catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Succsessfull");
        }
      }

       }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Pleas enter an availabe vehicle register number  " );
        }
         
      
     
         

    }//GEN-LAST:event_btnadd1ActionPerformed

    private void btnback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback1ActionPerformed
        // TODO add your handling code here:
        pnlcustomer_deitails1.setVisible(false);
        pnlvehicle_details1.setVisible(false);
        tblvehicle_details.setVisible(true);
        btnadd.setVisible(true);
        btnadd1.setVisible(false);
        pnlcustomer_details.setVisible(true);
        btnback1.setVisible(false);
        load_vehicle_table();
    }//GEN-LAST:event_btnback1ActionPerformed

    private void txtyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtyearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehicle_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehicle_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehicle_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehicle_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehicle_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnadd1;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnback1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbladress;
    private javax.swing.JLabel lblavailable;
    private javax.swing.JLabel lblavailable1;
    private javax.swing.JLabel lblbackground;
    private javax.swing.JLabel lblcustomer_details;
    private javax.swing.JLabel lblcustomer_regno;
    private javax.swing.JLabel lbldisplay;
    private javax.swing.JLabel lblmodel;
    private javax.swing.JLabel lblmodel1;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblnic;
    private javax.swing.JLabel lblno;
    private javax.swing.JLabel lblphone;
    private javax.swing.JLabel lblregno;
    private javax.swing.JLabel lblreleas_date1;
    private javax.swing.JLabel lblreted_date;
    private javax.swing.JLabel lblseats;
    private javax.swing.JLabel lbltype;
    private javax.swing.JLabel lblvehicle_detils;
    private javax.swing.JLabel lblvehicle_detils1;
    private javax.swing.JLabel lblveviclename;
    private javax.swing.JPanel pnlcustomer_deitails1;
    private javax.swing.JPanel pnlcustomer_details;
    private javax.swing.JPanel pnldetails;
    private javax.swing.JPanel pnlvehicle_details1;
    private javax.swing.JTable tblvehicle_details;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtcustomer_regno;
    private javax.swing.JTextField txtdriven;
    private javax.swing.JTextField txtmodel;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txtnumber;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtreg_no;
    private javax.swing.JTextField txtreleas_date;
    private javax.swing.JTextField txtrented_date;
    private javax.swing.JTextField txtseats;
    private javax.swing.JTextField txtvehicle_name;
    private javax.swing.JTextField txtyear;
    // End of variables declaration//GEN-END:variables
}
