/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author USER
 */
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import controls.Database;
import controls.ListItem;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class vehicle_add extends javax.swing.JFrame {
    public int v_id = 0;
    public int ve_id = 1;
    int reg;
    
    Connection con;
    PreparedStatement pst;
   
    /**
     * Creates new form vehicle_add
     */
    public vehicle_add() {
        initComponents();
       con=SQLCON.connect();
       load_section_combo();
       
       
    }
    
     private ArrayList<ListItem> combo(String query, String col_ID, String col_Name) throws Exception {
        ArrayList<ListItem> names = new ArrayList<>();
        Statement stmt = Database.getCon().createStatement();
        ResultSet rset = stmt.executeQuery(query);
        while (rset.next()) {
            ListItem item = new ListItem();
            item.setId(rset.getInt(col_ID));
            item.setName(rset.getString(col_Name));
            names.add(item);
        }
        return names;
    }
//-----------------------Load User Level Combo Function()-----------------------

     
     private void clear() {
       
       // txtcustomer_regno.requestFocus();
        
           txtname.setText("");
           txtnic.setText("");
           txtaddress.setText("");
           txtphone.setText("");
           txtvehicle_name.setText("");
           txtmodel.setText("");
           txtnumber.setText("");
           txtyear.setText("");
           txtseats.setText("");
           txtreg_no.setText("");
           txtvehicle_name.setText("");
           txtmodel.setText("");
           txtnumber.setText("");
           txtyear.setText("");
           txtseats.setText("");
    }
    private void load_section_combo() {
        try {
           
            String query = "SELECT owner_details.reg_no,owner_details.owner_name FROM owner_details ORDER BY owner_details.reg_no DESC";
            ArrayList<ListItem> itemsList = combo(query, "reg_no", "owner_name");
            DefaultComboBoxModel def = new DefaultComboBoxModel(itemsList.toArray());
           cmbowner_regno.setModel(def);
            //check_user_type();
            } 
        catch (Exception ex)
        {
            ex.printStackTrace();
        }
    }
     private void selectcmb(){
        
         try {
            ListItem user_type = (ListItem) cmbowner_regno.getSelectedItem();
            reg = user_type.getId();
           // load_customer_table(reg);
          //  load_pat_details(reg);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
         
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnback = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        pnlvehicle_details1 = new javax.swing.JPanel();
        lblmodel = new javax.swing.JLabel();
        lblmodel1 = new javax.swing.JLabel();
        lblno = new javax.swing.JLabel();
        lblveviclename = new javax.swing.JLabel();
        txtvehicle_name = new javax.swing.JTextField();
        txtmodel = new javax.swing.JTextField();
        txtyear = new javax.swing.JTextField();
        txtnumber = new javax.swing.JTextField();
        lblregno = new javax.swing.JLabel();
        txtreg_no = new javax.swing.JTextField();
        txtdriven = new javax.swing.JTextField();
        lblseats = new javax.swing.JLabel();
        txtseats = new javax.swing.JTextField();
        lbltype = new javax.swing.JLabel();
        cmbtype = new javax.swing.JComboBox();
        cmb_cat = new javax.swing.JComboBox();
        lblcat = new javax.swing.JLabel();
        cmbowner_regno = new javax.swing.JComboBox();
        lblvehicle_detils = new javax.swing.JLabel();
        pnlowner_details = new javax.swing.JPanel();
        lblowner_details = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lblnic = new javax.swing.JLabel();
        txtnic = new javax.swing.JTextField();
        lbladress = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        lblphone = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        btnregister = new javax.swing.JButton();
        lbldisplay = new javax.swing.JLabel();
        lblbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1025, 625));
        setResizable(false);
        getContentPane().setLayout(null);

        btnback.setBackground(new java.awt.Color(99, 3, 46));
        btnback.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnback.setForeground(new java.awt.Color(204, 204, 255));
        btnback.setText("back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback);
        btnback.setBounds(550, 500, 125, 40);

        btnadd.setBackground(new java.awt.Color(99, 3, 46));
        btnadd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnadd.setForeground(new java.awt.Color(204, 204, 255));
        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd);
        btnadd.setBounds(710, 500, 140, 40);

        pnlvehicle_details1.setBackground(new java.awt.Color(104, 94, 137));
        pnlvehicle_details1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        pnlvehicle_details1.setOpaque(false);

        lblmodel.setBackground(new java.awt.Color(255, 255, 255));
        lblmodel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblmodel.setForeground(new java.awt.Color(255, 255, 255));
        lblmodel.setText("Model :");

        lblmodel1.setBackground(new java.awt.Color(255, 255, 255));
        lblmodel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblmodel1.setForeground(new java.awt.Color(255, 255, 255));
        lblmodel1.setText("Year :");

        lblno.setBackground(new java.awt.Color(255, 255, 255));
        lblno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblno.setForeground(new java.awt.Color(255, 255, 255));
        lblno.setText("Number :");

        lblveviclename.setBackground(new java.awt.Color(255, 255, 255));
        lblveviclename.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblveviclename.setForeground(new java.awt.Color(255, 255, 255));
        lblveviclename.setText("Name :");

        txtvehicle_name.setBackground(new java.awt.Color(204, 204, 255));
        txtvehicle_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvehicle_nameActionPerformed(evt);
            }
        });

        txtmodel.setBackground(new java.awt.Color(204, 204, 255));

        txtyear.setBackground(new java.awt.Color(204, 204, 255));

        txtnumber.setBackground(new java.awt.Color(204, 204, 255));
        txtnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumberActionPerformed(evt);
            }
        });

        lblregno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblregno.setForeground(new java.awt.Color(255, 255, 255));
        lblregno.setText("Vehicle owner Reg. No :");

        txtreg_no.setEditable(false);
        txtreg_no.setBackground(new java.awt.Color(204, 204, 255));
        txtreg_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreg_noActionPerformed(evt);
            }
        });

        lblseats.setBackground(new java.awt.Color(255, 255, 255));
        lblseats.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblseats.setForeground(new java.awt.Color(255, 255, 255));
        lblseats.setText("Seats :");

        txtseats.setBackground(new java.awt.Color(204, 204, 255));

        lbltype.setBackground(new java.awt.Color(255, 255, 255));
        lbltype.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltype.setForeground(new java.awt.Color(255, 255, 255));
        lbltype.setText("Type :");

        cmbtype.setBackground(new java.awt.Color(255, 206, 108));
        cmbtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A/C", "Non A/c" }));

        cmb_cat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Car", "Van", "Lorry" }));
        cmb_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_catActionPerformed(evt);
            }
        });

        lblcat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcat.setForeground(new java.awt.Color(255, 255, 255));
        lblcat.setText("Catogary");

        cmbowner_regno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbowner_regnoItemStateChanged(evt);
            }
        });
        cmbowner_regno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbowner_regnoActionPerformed(evt);
            }
        });

        lblvehicle_detils.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblvehicle_detils.setForeground(new java.awt.Color(204, 204, 255));
        lblvehicle_detils.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblvehicle_detils.setText("Vehicle Details");

        javax.swing.GroupLayout pnlvehicle_details1Layout = new javax.swing.GroupLayout(pnlvehicle_details1);
        pnlvehicle_details1.setLayout(pnlvehicle_details1Layout);
        pnlvehicle_details1Layout.setHorizontalGroup(
            pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                                .addComponent(lblregno, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtreg_no, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbowner_regno, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblmodel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbltype, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblcat, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblseats, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblno, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblveviclename, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtvehicle_name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                                        .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtseats, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(615, 615, 615)
                                        .addComponent(txtdriven, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cmbtype, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtmodel, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                        .addComponent(cmb_cat, 0, 160, Short.MAX_VALUE))))))
                    .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(lblvehicle_detils, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlvehicle_details1Layout.setVerticalGroup(
            pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lblvehicle_detils)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtreg_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblregno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbowner_regno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcat, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblveviclename)
                    .addComponent(txtvehicle_name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmodel))
                .addGap(18, 18, 18)
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblno)
                    .addComponent(txtnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                        .addComponent(txtdriven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                        .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmodel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtseats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblseats))
                        .addGap(18, 18, 18)))
                .addGroup(pnlvehicle_details1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltype)
                    .addGroup(pnlvehicle_details1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(cmbtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );

        getContentPane().add(pnlvehicle_details1);
        pnlvehicle_details1.setBounds(440, 50, 450, 436);

        pnlowner_details.setBackground(new java.awt.Color(204, 204, 255));
        pnlowner_details.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        pnlowner_details.setOpaque(false);

        lblowner_details.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblowner_details.setForeground(new java.awt.Color(204, 204, 255));
        lblowner_details.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblowner_details.setText("About Owner");
        lblowner_details.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblname.setForeground(new java.awt.Color(255, 255, 255));
        lblname.setText("Name :");

        txtname.setBackground(new java.awt.Color(204, 204, 255));

        lblnic.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblnic.setForeground(new java.awt.Color(255, 255, 255));
        lblnic.setText("NIC :");

        txtnic.setBackground(new java.awt.Color(204, 204, 255));
        txtnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnicActionPerformed(evt);
            }
        });

        lbladress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbladress.setForeground(new java.awt.Color(255, 255, 255));
        lbladress.setText("Adress :");

        txtaddress.setBackground(new java.awt.Color(204, 204, 255));
        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });

        lblphone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblphone.setForeground(new java.awt.Color(255, 255, 255));
        lblphone.setText("Phone NO. :");

        txtphone.setBackground(new java.awt.Color(204, 204, 255));
        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });

        btnregister.setText("Reister");
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlowner_detailsLayout = new javax.swing.GroupLayout(pnlowner_details);
        pnlowner_details.setLayout(pnlowner_detailsLayout);
        pnlowner_detailsLayout.setHorizontalGroup(
            pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(lblowner_details, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnregister)
                            .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                                    .addComponent(lbladress, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                                    .addComponent(lblphone, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                                    .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblnic, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(26, 26, 26)
                                    .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        pnlowner_detailsLayout.setVerticalGroup(
            pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlowner_detailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblowner_details, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblname))
                .addGap(34, 34, 34)
                .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnic))
                .addGap(35, 35, 35)
                .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbladress)
                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(pnlowner_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblphone)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(btnregister)
                .addGap(69, 69, 69))
        );

        getContentPane().add(pnlowner_details);
        pnlowner_details.setBounds(30, 50, 380, 440);

        lbldisplay.setDisplayedMnemonic('A');
        lbldisplay.setFont(new java.awt.Font("Stencil", 2, 36)); // NOI18N
        lbldisplay.setForeground(new java.awt.Color(102, 255, 255));
        lbldisplay.setText("VEhicle Rental System");
        getContentPane().add(lbldisplay);
        lbldisplay.setBounds(230, 0, 450, 50);

        lblbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        getContentPane().add(lblbackground);
        lblbackground.setBounds(0, 0, 1000, 580);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
         new Vehicle_details().setVisible(true);
        this.dispose();


     //if (txtvehicle_name.getText().trim().isEmpty() ) {
            //    JOptionPane.showMessageDialog(this, "Register the vehicle !", "Message", JOptionPane.ERROR_MESSAGE);
            //    txtvehicle_name.requestFocus();
            //    return;
         //  } 
    // else{
      //   new Vehicle_details().setVisible(true);
      //  this.dispose();
   //  }
        
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        //ehicle save function
 
     String sql="INSERT INTO vehicle_details(owner_reg_no,vehi_cat,name,model,year,number,seats,type,states)VALUES (?,?,?,?,?,?,?,?,?)";
    try
        {
     if (txtreg_no.getText().trim().isEmpty() ) {
                JOptionPane.showMessageDialog(this, "Vehicle can not register without owner !", "Message", JOptionPane.ERROR_MESSAGE);
                txtreg_no.requestFocus();
                return;
           }  
    
            pst=con.prepareStatement(sql);
            pst.setString(1,txtreg_no.getText());
            pst.setString(2,cmb_cat.getSelectedItem().toString());
            pst.setString(3,txtvehicle_name.getText());
            pst.setString(4,txtmodel.getText());
            pst.setString(5,txtyear.getText());
            pst.setString(6,txtnumber.getText()); 
            pst.setString(7,txtseats.getText()); 
            pst.setString(8,cmbtype.getSelectedItem().toString()); 
            pst.setInt(9, v_id);
    
    
    pst.execute();
    JOptionPane.showMessageDialog(null,"Successfuly added");
      
            }
                catch(Exception e)
                        {
                            JOptionPane.showMessageDialog(null,e);
                        }


       
 clear();
        
    }//GEN-LAST:event_btnaddActionPerformed

    private void txtvehicle_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvehicle_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvehicle_nameActionPerformed

    private void txtreg_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreg_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtreg_noActionPerformed

    private void txtnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnicActionPerformed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
        // TODO add your handling code here:
        //vehicle owner register function
        //String type=cmbtype.getSelectedItem().toString();
     try
{           
                
          if (txtnic.getText().trim().isEmpty() ) {
                JOptionPane.showMessageDialog(this, "Owner nic can not be Empty", "Message", JOptionPane.ERROR_MESSAGE);
                txtnic.requestFocus();
                return;
           }  
           if (txtname.getText().trim().isEmpty() ) {
                JOptionPane.showMessageDialog(this, "Owner name can not be Empty", "Message", JOptionPane.ERROR_MESSAGE);
                txtname.requestFocus();
                return;
           }  
           
           if (txtaddress.getText().trim().isEmpty() ) {
                JOptionPane.showMessageDialog(this, "Owner address can not be Empty", "Message", JOptionPane.ERROR_MESSAGE);
                txtaddress.requestFocus();
                return;
           }  
           if (txtphone.getText().trim().isEmpty() ) {
                JOptionPane.showMessageDialog(this, "Owner phone number can not be Empty", "Message", JOptionPane.ERROR_MESSAGE);
                txtphone.requestFocus();
                return;
           }  
          
          
        String sql="INSERT INTO owner_details (owner_name,nic,address,phone) VALUES (?,?,?,?)";

            pst=con.prepareStatement(sql);
           
             
            pst.setString(1,txtname.getText());
            pst.setString(2,txtnic.getText());
            pst.setString(3,txtaddress.getText());
            pst.setString(4,txtphone.getText());
           
            
              pst.execute();
    
    JOptionPane.showMessageDialog(null,"Successfuly added");
    
    


         try
        {
            Statement st=con.createStatement();
            String nic=txtnic.getText();

            String sql1="SELECT * FROM owner_details WHERE nic='"+nic+"'";
            ResultSet rs=st.executeQuery(sql1);

            if(rs.next()==false)
            {
               
                JOptionPane.showMessageDialog(null, "Invalid register");
            }
           
             int reg =rs.getInt("reg_no");
            txtreg_no.setText(String.valueOf(reg));

            
            
            
        }
       
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

}  

                catch(Exception e)
                {
                            JOptionPane.showMessageDialog(null,e);
                        } 


    }//GEN-LAST:event_btnregisterActionPerformed

    private void txtnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumberActionPerformed

    private void cmbowner_regnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbowner_regnoActionPerformed
        // TODO add your handling code here:
        try{
              
           Statement st=con.createStatement();
           String owner_name=cmbowner_regno.getSelectedItem().toString();
              
            String sql="SELECT * FROM owner_details WHERE owner_name='"+owner_name+"' ORDER BY owner_details.reg_no DESC ";
            ResultSet rs=st.executeQuery(sql);

            if(rs.next()==false)
            {
                JOptionPane.showMessageDialog(null, "Invalid rgister number");
            }
            String reg=rs.getString("reg_no");
            txtreg_no.setText(reg);
            
             String name=rs.getString("owner_name");
            txtname.setText(name);

            String address=rs.getString("address");
            txtaddress.setText(address);
            
            String nic=rs.getString("nic");
            txtnic.setText(nic);
            
             
            String phone=rs.getString("phone");
            txtphone.setText(phone);
        }
        
        catch(Exception e)
                {
                     JOptionPane.showMessageDialog(null,e);
                 }
        
    }//GEN-LAST:event_cmbowner_regnoActionPerformed

    private void cmb_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_catActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_catActionPerformed

    private void cmbowner_regnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbowner_regnoItemStateChanged
        // TODO add your handling code here:
        selectcmb();
        
    }//GEN-LAST:event_cmbowner_regnoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vehicle_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vehicle_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vehicle_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vehicle_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vehicle_add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnregister;
    private javax.swing.JComboBox cmb_cat;
    private javax.swing.JComboBox cmbowner_regno;
    private javax.swing.JComboBox cmbtype;
    private javax.swing.JLabel lbladress;
    private javax.swing.JLabel lblbackground;
    private javax.swing.JLabel lblcat;
    private javax.swing.JLabel lbldisplay;
    private javax.swing.JLabel lblmodel;
    private javax.swing.JLabel lblmodel1;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblnic;
    private javax.swing.JLabel lblno;
    private javax.swing.JLabel lblowner_details;
    private javax.swing.JLabel lblphone;
    private javax.swing.JLabel lblregno;
    private javax.swing.JLabel lblseats;
    private javax.swing.JLabel lbltype;
    private javax.swing.JLabel lblvehicle_detils;
    private javax.swing.JLabel lblveviclename;
    private javax.swing.JPanel pnlowner_details;
    private javax.swing.JPanel pnlvehicle_details1;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtdriven;
    private javax.swing.JTextField txtmodel;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txtnumber;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtreg_no;
    private javax.swing.JTextField txtseats;
    private javax.swing.JTextField txtvehicle_name;
    private javax.swing.JTextField txtyear;
    // End of variables declaration//GEN-END:variables
}
